# Generated by Django 5.0.4 on 2024-08-08 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_author_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
